version: "3"

services:
  sql-db:
    image: postgres:16.3
    command: postgres -c max_connections=200
    ports:
      - target: 5432
        published: 5438
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_DB: social
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: adminpassword
