
run-app:
	@echo "Running the app..."
	go run src/services/backend/cmd/api/*.go

run-live-reload:
	@echo "Running the app with live reload..."
	
	cd src/services/backend && /Users/divakar.patil/go/bin/air -c .air.toml
